---
title: "imitate"
author: "zhuofan wang"
date: "2021/8/7"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{R warning=FALSE}
#package prepared
library(EnvStats)
library(mgcv)
library(microbenchmark)
library(MASS)
library(BayesLogit)
#microbenchmark(power_iter(A),power_iter_sparse(A_spar),times = 10)
```
```{r}
n <- 40
T <- 50
sigma_inv_prior <- function(A,Q){
  Sigma <- matrix(0,nrow = T,ncol = T)
  diag(Sigma) <- 1+A^2
  sdiag(Sigma,1) <- -A
  sdiag(Sigma,-1) <- -A
  Sigma[T,T] <- 1
  Sigma[1,1] <- 1
  return(Sigma/Q)
}

#function to calculate mean of polya-gamma variable PG(1,x)
mpg <- function(x){
  return((exp(x)-1)/(2*x*(1+exp(x))))
}


#function to calculate the element-wise product of z_i and z_j, i.e.in_prod[i,j,t] = z[t,i]*z[t,j] 
#input z is a matrix of t $\times$ n
in_prod <- function(z){
  temp <- apply(z, 2, function(v){return(apply(z, 2, function(u){return(u*v)}))})
  temp <- array(temp,dim = c(T,n,n))
  temp <- aperm(temp,perm = c(2,3,1))
  temp <- apply(temp, 3, function(t){
    diag(t) <- 0
    return(t)})
  temp <- array(temp,dim = c(n,n,T))
  return(temp)
}


#function to derive the al_sum, whhere al_sum[i,j,t]=alpha[i]+alpha[j]
al_sum_f <- function(alpha){
  al_matrix <- matrix(rep(alpha,n),nrow = n)
  al_matrix <- al_matrix+t(al_matrix)
  al_array <- array(rep(al_matrix,T),dim = c(n,n,T))
  return(al_array)
}


#function to calculate E(theta^2)(note:Ez2[t,i] = Ez[i,t]^2)
Etheta2 <- function(alpha,mu,Ez2){
  al_sum <- al_sum_f(alpha)
  result <- in_prod(Ez2)+2*al_sum*in_prod(mu)+al_sum^2
  return(sqrt(result))
}
```

```{r}

T <- 50
n <- 40
#alpha <- runif(n,min = 1,max = 3)
#alpha <- -alpha/sum(alpha)
#al_sum <- al_sum_f(alpha)

A <- 0.8*diag(n)


#mu1 <- -1
#mu2 <- 1
z <- matrix(0, nrow = n, ncol =T)
#z[1:(n/2),1] <- mu1
#z[(n/2+1):n,1] <- mu2
z[,1] <- rnorm(n)
for (t in 2:T) {
  z[,t] <- A%*%z[,t-1]+0.6*rnorm(n,0,1)
}
z_prod <- in_prod(t(z))

theta <- array(0,c(n,n,T))

Y <- array(0,c(n,n,T))

theta <- z_prod
for (t in 1:T) {
  for (i in 1:(n-1)) {
   for (j in (i+1):n) {

    Y[i,j,t] <- rbinom(1,1,plogis(theta[i,j,t]))
  }
}
 Y[,,t][lower.tri(Y[,,t])] <- t(Y[,,t])[lower.tri(t(Y[,,t]))]
 
}

Kappa <- apply(Y,1,function(m){return(m)})-0.5

```

```{r}
gibbs_sample <- function(ns,nd,n,T,Kappa,zinit,A,Q){
  z0 <- zinit
  zsample <- matrix(0,nrow = (ns+nd)*T,ncol = n)
  for (l in 1:(ns+nd)) {
    for (i in 1:n) {
      zi <- z0[,i]
      omegai <- matrix(0,nrow = T,ncol = T)
      psi <- rep(0,T)
      wi <- matrix(0,nrow = T,ncol = n)
      for (j in 1:n) {
        bd <- matrix(0,nrow = T,ncol = T)
        zj <- z0[,j]
        wij <- rep(0,T)
        for (t in 1:T) {
          c <- zi[t]*zj[t]
          wij[t] <- rpg(1,1,c)
          if(j==i)
            wij[t] <- 0
          bd[t,t] <- wij[t]*zj[t]^2
          psi[t] <- psi[t]+Kappa[(t-1)*n+i,j]*zj[t]
          
        }
        wi[,j] <- wij
        omegai <- omegai+bd
        
      }
      vi <- sigma_inv_prior(A,Q)
      vipost <- solve(vi+omegai)
      meanipost <- vipost%*%psi
      z0[,i] <- mvrnorm(1,meanipost,vipost)
      
    }
    zsample[((l-1)*T+1):(l*T),] <- z0
  }
  return(zsample)
}

```

```{r}
u <- 0.1*matrix(rnorm(T*n),nrow=T,ncol=n)
zgibbs <- gibbs_sample(1000,1000,20,50,Kappa,u,0.9,0.9^2)
mui <- apply(zr, c(1,2),mean)
sigmai <- apply(zr, 2, function(x){return(cov(t(x)))})
sigmai <- array(sigmai,dim = c(T,T,n))
zresult2 <- array(zgibbs,dim = c(50,2000,100))
zr <- aperm(zresult2,c(1,3,2))
zr <- zr[,,-(1:1000)]


v <- sigmai[,,1]
```
```{r}
par(mfrow=c(3,2))
plot(mui[,1])
plot(z[1,])
plot(mui[,2])
plot(z[2,])
plot(mui[,3])
plot(z[3,])
```
```{r}
f1 <- 0
f2 <- 0
f3 <- 0
for (i in 1:n) {
  for (t in 2:T) {
    for (k in 1:1000) {
      f1 <- f1+zr[t,i,k]*zr[t-1,i,k]
      f2 <- f2+zr[t-1,i,k]^2
      f3 <- f3+(zr[t,i,k]-Aem*zr[t-1,i,k])^2
    }
  }
}
f1/f2
(f3-(f1/f2)^2*f2)/(20*49*1000)

```

```{r}
Ecros <- sum(mui[-1,]*mui[-T,]+apply(sigmai,3,function(s){return(sdiag(s,1))}))

Eself <- mui*mui+apply(sigmai,3,function(s){return(diag(s))})


  
  A_em <- Ecros/sum(Eself[-T,])
  
  
  
  Q_em <- (sum(Eself[-1,])-A_em^2*sum(Eself[-T,]))/(n*(T-1))
  A_em
  Q_em
```

```{r}
Aem <- 0.9
Qem <- 0.8
Atrack <- rep(0,50)
Qtrack <- rep(0,50)
for (iter in 1:50) {
  u <- matrix(rnorm(T*n),nrow=T,ncol=n)
  
  zgibbs <- gibbs_sample(1000,1000,20,50,Kappa,u,Aem,Qem)
  zresult2 <- array(zgibbs,dim = c(50,2000,20))
  zr <- aperm(zresult2,c(1,3,2))
  zr <- zr[,,-(1:1000)]


  mui <- apply(zr, c(1,2),mean)
  sigmai <- apply(zr, 2, function(x){return(cov(t(x)))})
  sigmai <- array(sigmai,dim = c(T,T,n))
  Ecros <- sum(mui[-1,]*mui[-T,]+apply(sigmai,3,function(s){return(sdiag(s,1))}))

  Eself <- mui*mui+apply(sigmai,3,function(s){return(diag(s))})

  Aem <- Ecros/sum(Eself[-T,])

  Qem <- (sum(Eself[-1,])-A_em^2*sum(Eself[-T,]))/(n*(T-1))
  Atrack[iter] <- Aem
  Qtrack[iter] <- Qem
}

```

```{r}
par(mfrow=c(1,2))
plot(Atrack)
plot(Qtrack)
```

```{r}
A_em <- 0.8
Q_em <- 0.5
zgibbs <- GibbsSample_cpp(1000,1000,1,100,50,Kappa,u,as.matrix(A_em),as.matrix(Q_em))

```

```{r}
EMalg(500,500,1,40,50,Kappa+0.5,as.matrix(0.9),as.matrix(0.8),50,1e-3)

```