---
title: "VariationalEM"
author: "zhuofan wang"
date: "2021/7/19"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{R warning=FALSE}
#package prepared
library(EnvStats)
library(mgcv)
library(microbenchmark)
#microbenchmark(power_iter(A),power_iter_sparse(A_spar),times = 10)
```


```{r}
#function prepared

#get function of AR prior precision matrix (inverse of covariance matrix)

sigma_inv_prior <- function(A,Q){
  Sigma <- matrix(0,nrow = T,ncol = T)
  diag(Sigma) <- 1+A^2
  sdiag(Sigma,1) <- -A
  sdiag(Sigma,-1) <- -A
  Sigma[T,T] <- 1
  Sigma[1,1] <- 1
  return(Sigma/Q)
}



#function to calculate mean of polya-gamma variable PG(1,x)
mpg <- function(x){
  return((exp(x)-1)/(2*x*(1+exp(x))))
}


#function to calculate the element-wise product of z_i and z_j, i.e.in_prod[i,j,t] = z[t,i]*z[t,j] 
#input z is a matrix of t $\times$ n
in_prod <- function(z){
  temp <- apply(z, 2, function(v){return(apply(z, 2, function(u){return(u*v)}))})
  temp <- array(temp,dim = c(T,n,n))
  temp <- aperm(temp,perm = c(2,3,1))
  temp <- apply(temp, 3, function(t){
    diag(t) <- 0
    return(t)})
  temp <- array(temp,dim = c(n,n,T))
  return(temp)
}


#function to derive the al_sum, whhere al_sum[i,j,t]=alpha[i]+alpha[j]
al_sum_f <- function(alpha){
  al_matrix <- matrix(rep(alpha,n),nrow = n)
  al_matrix <- al_matrix+t(al_matrix)
  al_array <- array(rep(al_matrix,T),dim = c(n,n,T))
  return(al_array)
}


#function to calculate E(theta^2)(note:Ez2[t,i] = Ez[i,t]^2)
Etheta2 <- function(alpha,mu,Ez2){
  al_sum <- al_sum_f(alpha)
  result <- in_prod(Ez2)+2*al_sum*in_prod(mu)+al_sum^2
  return(sqrt(result))
}


```

---------------Data generation----------------


```{r}

T <- 50
n <- 20
alpha <- runif(n,min = 1,max = 3)
alpha <- -alpha/sum(alpha)
al_sum <- al_sum_f(alpha)

A <- 0.6*diag(n)


#mu1 <- -1
#mu2 <- 1
z <- matrix(0, nrow = n, ncol =T)
#z[1:(n/2),1] <- mu1
#z[(n/2+1):n,1] <- mu2
z[,1] <- rnorm(n)
for (t in 2:T) {
  z[,t] <- A%*%z[,t-1]+0.7*rnorm(n,0,1)
}
z_prod <- in_prod(t(z))

theta <- array(0,c(n,n,T))

Y <- array(0,c(n,n,T))

theta <- al_sum+z_prod
for (t in 1:T) {
  for (i in 1:(n-1)) {
   for (j in (i+1):n) {

    Y[i,j,t] <- rbinom(1,1,plogis(theta[i,j,t]))
  }
}
 Y[,,t][lower.tri(Y[,,t])] <- t(Y[,,t])[lower.tri(t(Y[,,t]))]
 
}

Kappa <- apply(Y,1,function(m){return(m)})-0.5

```

---------------Variational EM-----------------


------------------E-step:CAVI iteration-------------------


------initialization------

```{r}
A_em <- 0.9
Q_em <- 0.8


U <- matrix(rnorm(T*n),nrow=T,ncol=n)


```

```{r}

#iteration
VE <- function(A_em,Q_em,alpha_em,k){
  mu_cavi <- array(rnorm(T*n),dim = c(T,n))
  
  sigma_cavi <- array(0,dim = c(T,T,n))
  
  varz <- apply(sigma_cavi, 3, function(s){return(diag(s))})
  
  
  Ez2 <- mu_cavi^2+varz

  
  Omega <- array(0.1,dim = c(n,n,T))
  
  alem_sum <- al_sum_f(alpha_em)
  

  for (iter in 1:k) {
   Ew <- mpg(Omega)
   temp <- mu_cavi
    for (i in 1:n) {
    
      sp_inv <- sigma_inv_prior(A_em,Q_em)
      #mu_pr <- sp_inv%*%mu1[i,]
      

      phi_inv <- colSums(Ew[i,-i,]*t(Ez2[,-i]))
      psi <- colSums((Y[i,-i,]-0.5-Ew[i,-i,]*alem_sum[i,-i,])*t(mu_cavi[,-i]))
    
    
      diag(sp_inv) <- diag(sp_inv)+phi_inv
      sigma_cavi[,,i] <- solve(sp_inv)
      mu_cavi[,i] <- sigma_cavi[,,i]%*%(psi)
      varz[,i] <- diag(sigma_cavi[,,i])
      Ez2[,i] <- mu_cavi[,i]^2+varz[,i]
    
   
    }
   if(norm(mu_cavi,type = "F")^2<10e-8*n*T){
     mu_cavi <- 0
     break
   }
   if(norm(temp-mu_cavi,type = "F")^2/norm(mu_cavi,type = "F")^2<0.0005)
     break
  Omega <- Etheta2(alpha_em,mu_cavi,Ez2)
  
  }
  
  result <- list()
  result[["mu"]] <- mu_cavi
  result[["sigma"]] <- sigma_cavi
  result[["Ew"]] <- Ew
  result[["Ez2"]] <- Ez2
  return(result)
}

```


```{r}
plot(mu_cavi[1,])
plot(mu_cavi[2,])
plot(mu_cavi[,1])
plot(z[1,])
```

---------------------------M-step--------------------------
```{R}
VM <- function(mu_cavi,sigma_cavi,Ew,Ez2){
  #sdiag:function in package "mgcv" to derive the super-diag of matrix
  
  Ecros <- sum(mu_cavi[-1,]*mu_cavi[-T,]+apply(sigma_cavi,3,function(s){return(sdiag(s,1))}))
  
  
  A_em <- Ecros/sum(Ez2[-T,])
  
  
  
  Q_em <- sqrt((sum(Ez2[-1,])-A_em^2*sum(Ez2[-T,]))/(n*(T-1)))
  #S <- apply(Ew,c(1,2),sum)
  #Q_em <- 1
  
  #diag(S) <- 0
  #diag(S) <- 0.5*rowSums(S)
  
  
  #lm <- Y-0.5-Ew*(in_prod(mu_cavi))
  #del <- apply(lm, 3, function(s){return(diag(s))})
  
  
  #l <- apply(lm,1,sum) - rowSums(del)
  #alpha_em <- 0.5*solve(S,l)
  alpha_em <- alpha
  result <- list()
  result[["A"]] <- A_em
  result[["alpha"]] <- alpha_em
  result[["Q"]] <- Q_em
  return(result)
}

  
```

---------VEM---------


```{R eval=FALSE, include=FALSE}
m <- 100
for (v in 1:m) {
  r1 <- VE(A_em,Q_em, alpha_em,100)
  mu_cavi <- r1$mu
  if(sum(mu_cavi^2)==0)
    break
  sigma_cavi <- r1$sigma
  Ew <- r1$Ew
  Ez2 <- r1$Ez2
  r2 <- VM(mu_cavi,sigma_cavi,Ew,Ez2)
  temp1 <- A_em
  temp2 <- Q_em
  A_em <- r2$A
  alpha_em <- r2$alpha
  Q_em <- r2$Q
  if(((abs(A_em-temp1)/A_em)<0.01)&((abs(Q_em-temp2)/Q_em)<0.01))
    break
}


```


----------you can ignore the text below(just for repetition)------------


```{r eval=FALSE, include=FALSE}
dat_gen <- function(A,Q,alpha){
T <- 100
n <- 20


al_sum <- al_sum_f(alpha)

A <- A*diag(n)


#mu1 <- -1
#mu2 <- 1
z <- matrix(0, nrow = n, ncol =T)
#z[1:(n/2),1] <- mu1+rnormTrunc(n/2,0,1,min = -2,max = 2)
#z[(n/2+1):n,1] <- mu2+rnormTrunc(n/2,0,1,min = -2,max = 2)
z[,1] <- rnorm(n,0,1)
for (t in 2:T) {
  z[,t] <- A%*%z[,t-1]+Q*rnorm(n,0,1)
}
z_prod <- in_prod(t(z))

theta <- array(0,c(n,n,T))

Y <- array(0,c(n,n,T))

theta <- al_sum+z_prod
for (t in 1:T) {
  for (i in 1:(n-1)) {
   for (j in (i+1):n) {

    Y[i,j,t] <- rbinom(1,1,plogis(theta[i,j,t]))
  }
}
 Y[,,t][lower.tri(Y[,,t])] <- t(Y[,,t])[lower.tri(t(Y[,,t]))]
 
}
return(Y)
}

```


```{r eval=FALSE, include=FALSE}
result1 <- rep(0,10)
result2 <- rep(0,10)
for (r in 1:50) {
  
    alpha <- runif(n,min = 1,max = 3)
    alpha <- -alpha/sum(alpha)
    Y <- dat_gen(0.6,0.6,alpha)
    A_em <- 0.9
      Q_em <- 0.8
      alpha_em <- alpha


    m <- 50
    for (v in 1:m) {
      r1 <- VE(A_em,Q_em, alpha_em,100)
      mu_cavi <- r1$mu
      if(sum(mu_cavi^2)==0)
        break
      sigma_cavi <- r1$sigma
      Ew <- r1$Ew
      Ez2 <- r1$Ez2
      r2 <- VM(mu_cavi,sigma_cavi,Ew,Ez2)
      temp1 <- A_em
      temp2 <- Q_em
      A_em <- r2$A
      alpha_em <- r2$alpha
      Q_em <- r2$Q
      if(((abs(A_em-temp1)/A_em)<0.001)&((abs(Q_em-temp2)/Q_em)<0.001))
        break
    }
    result1[r] <- A_em
    result2[r] <- Q_em
  
}

```

```{r}
par(mfrow=c(1,2))
boxplot(A_result)
boxplot(Q_result)

```

```{r}
zresult <- GibbsSample_cpp(1000,1000,1,20,50,Kappa,0.4*U,as.matrix(A_em),as.matrix(Q_em))

zresult2 <- array(zresult,dim = c(50,2000,20))
zr <- aperm(zresult2,c(1,3,2))
zr <- zr[,,-(1:1000)]


mui <- apply(zr, c(1,2),mean)
sigmai <- apply(zr, 2, function(x){return(cov(t(x)))})
sigmai <- array(sigmai,dim = c(T,T,n))
v <- sigmai[,,1]
```
```{r}
par(mfrow=c(3,2))
plot(mui[,1])
plot(z[1,])
plot(mui[,2])
plot(z[2,])
plot(mui[,3])
plot(z[3,])
```
```{r}
f1 <- 0
f2 <- 0
f3 <- 0
for (i in 1:n) {
  for (t in 2:T) {
    for (k in 1:1000) {
      f1 <- f1+zr[t,i,k]*zr[t-1,i,k]
      f2 <- f2+zr[t-1,i,k]^2
      f3 <- f3+zr[t,i,k]^2
    }
  }
}
f1/f2
(f3-(f1/f2)^2*f2)/(20*49*1000)

```

```{r}
Ecros <- sum(mui[-1,]*mui[-T,]+apply(sigmai,3,function(s){return(sdiag(s,1))}))

Eself <- mui*mui+apply(sigmai,3,function(s){return(diag(s))})


  
  A_em <- Ecros/sum(Eself[-T,])
  
  
  
  Q_em <- (sum(Eself[-1,])-A_em^2*sum(Eself[-T,]))/(n*(T-1))
  A_em
  Q_em
```
