---
title: "var-version for gbme"
author: "zhuofan wang"
date: "2021/9/20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#library(mlegp)
library(MASS)
library(mvtnorm)
library(BayesLogit)
library(reshape2)
library(zoo)
```

```{r}
#set parameters
T <-40
n <- 15

```

```{R}
#get function of exponential covariance matrix
covm <- function(g,k,t1,t2){
  res <- g*exp(-k*(t1-t2)^2)
  return(res)
}
```

```{R}
#get function of gaussian process samples
gp <- function(from,to,g,k,K,start,m){
  t <- seq(from=from,to=to,length.out = m)
  Sigma <- sapply(t, function(t1){
    sapply(t, function(t2){
      K(g,k,t1,t2)
    })
  })
  path <- mvrnorm(mu = rep(0,times=m),Sigma=Sigma)
  if(!is.null(start))
    path <- path-path[1]+start
  return(as.vector(path))
}
```

```{R}
#generating mu prior,x1_prior,x2_prior
set.seed(1)
mupri <- gp(1,T,1,0.05,covm,NULL,T)
x1 <- matrix(0,nrow = n,ncol = T)
x2 <- matrix(0,nrow = n,ncol = T)
x3 <- matrix(0,nrow = n,ncol = T)
for (i in (1:n)) {
  x1[i,] <- gp(1,T,1,0.05,covm,NULL,(T))
  x2[i,] <- gp(1,T,1,0.05,covm,NULL,(T))
  x3[i,] <- gp(1,T,1,0.05,covm,NULL,(T))
}
x <- list("x1"=x1,"x2"=x2)
```

```{r}
d <- data.frame("t" <- 1:T,"path"=mupri)
plot(d,type="l")
```

```{r}

#generating s_{ijt},pi_{ijt},y_{ijt}

s <- list()
pi <- list()
y <- list()
for (t in (1:T)) {
  temp1 <- matrix(0,nrow = n,ncol = n)
  
  temp2 <- matrix(0,nrow = n,ncol = n)
  temp3 <- matrix(0,nrow = n,ncol = n)
  for (i in (2:n)) {
    for (j in (1:(i-1))) {
      temp1[j,i] <- mupri[t]+x1[i,t]*x1[j,t]#+x2[i,t]*x2[j,t]
      temp2[j,i] <- 1/(1+exp(-temp1[j,i]))
      temp3[j,i] <- rbinom(1,1,temp2[j,i])
    }
  }
  s[[t]] <- temp1
  pi[[t]] <- temp2
  y[[t]] <- temp3
}
z <- array(0,dim = c(n,n,(T)))
for (t in 1:T) {
  for (i in (2:n)) {
    for (j in 1:(i-1)) {
      z[j,i,t] <- y[[t]][j,i]
    }
  }
   z[,,t][lower.tri(z[,,t])] <- t(z[,,t])[lower.tri(t(z[,,t]))]
}
y <- z
```


#prior covariance matrix
```{r}
#hyperparameter
T <- 40
kmu <- 0.1
kx <- 0.1
covm <- function(g,k,t1,t2){
  res <- g*exp(-k*(t1-t2)^2)
  return(res)
}
KMU <- sapply(1:T, function(t1){
    sapply(1:T, function(t2){
      covm(1,kmu,t1,t2)
    })
  })
KX <- sapply(1:T, function(t1){
    sapply(1:T, function(t2){
      covm(1,kx,t1,t2)
    })
  })
in_prod <- function(z){
  temp <- apply(z, 2, function(v){return(apply(z, 2, function(u){return(u*v)}))})
  temp <- array(temp,dim = c(T,n,n))
  temp <- aperm(temp,perm = c(2,3,1))
  temp <- apply(temp, 3, function(t){
    diag(t) <- 0
    return(t)})
  temp <- array(temp,dim = c(n,n,T))
  return(temp)
}
```


```{r}
vem <- function(n,T,iter,KMU,KX,y){
  #initialize
  
  beta <- rep(0,T)
  
  mu_x <- matrix(rnorm(n*T),nrow = n,ncol = T)
  var_x <- matrix(rnorm(n*T),nrow = n,ncol = T)
  m2_x <- mu_x^2+var_x
  w <- array(0.25,dim = c(n,n,T))
  
  for (k in 1:iter) {
    beta_old <- beta
    temp <- solve(solve(KMU)+0.5*diag(apply(w,3,sum)))
    betat <-0.5*apply(y-w*in_prod(t(mu_x)),3,sum)-0.25*n*(n-1)
    beta <- temp%*%betat
    for (i in 1:n) {
    temp1 <- solve(solve(KX)+diag(colSums(w[i,-i,]*m2_x[-i,])))
    temp2 <- colSums((y[i,-i,]-0.5-sweep(w[i,-i,],2,beta,"*"))*mu_x[-i,])
    mu_x[i,] <- temp1%*%temp2
    var_x[i,] <- diag(temp1)
    for (j in 1:i ) {
      
      for (t in 1:T) {
        c <- beta[t]+mu_x[i,t]*mu_x[j,t]
        w[i,j,t] <- tanh(0.5*c)/(2*c)
        w[i,i,t] <- 0
        w[j,i,t] <- w[i,j,t]
      }
    }
    }
    if(norm(beta-beta_old)/norm(beta) <0.001*T)
      break
  }
  return(beta)
}


```

```{r}
result_vem <- vem(15,40,100,KMU,KX,y)

```

```{r}
plot(result_vem)
lines(mupri)
```


{ Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz }4 core
#repetation
```{r}
result <- matrix(0,nrow = 40,ncol = 100)
time_vem <- rep(0,100)
mse <- rep(0,100)
for (sp in 1:100) {
  set.seed(sp)
  s <- list()
  pi <- list()
  y <- list()
  for (t in (1:T)) {
    temp1 <- matrix(0,nrow = n,ncol = n)
  
    temp2 <- matrix(0,nrow = n,ncol = n)
    temp3 <- matrix(0,nrow = n,ncol = n)
    for (i in (2:n)) {
      for (j in (1:(i-1))) {
        temp1[j,i] <- mupri[t]+x1[i,t]*x1[j,t]+x2[i,t]*x2[j,t]
        temp2[j,i] <- 1/(1+exp(-temp1[j,i]))
        temp3[j,i] <- rbinom(1,1,temp2[j,i])
      }
    }
    s[[t]] <- temp1
    pi[[t]] <- temp2
    y[[t]] <- temp3
  }
  z <- array(0,dim = c(n,n,(T)))
for (t in 1:T) {
  for (i in (2:n)) {
    for (j in 1:(i-1)) {
      z[j,i,t] <- y[[t]][j,i]
    }
  }
   z[,,t][lower.tri(z[,,t])] <- t(z[,,t])[lower.tri(t(z[,,t]))]
}
y <- z
result_vem <- vem(15,40,100,KMU,KX,y)
mse[sp] <- norm(result_vem-mupri,type = "2")
result[,sp] <- result_vem
time_vem[sp] <- system.time(vem(15,40,100,KMU,KX,y))[3]
}
```

```{r}
par(mfrow = c(1,2))
plot(result[,which.min(mse)])
lines(mupri)
plot(result[,which.min(abs(mse-median(mse)))])
lines(mupri)
```

```{r}
quantile(time_vem)
```


```{r}
#set parameters
T <-80
n <- 100

```

```{R}
#generating mu prior,x1_prior,x2_prior
set.seed(1)
mupri <- gp(1,T,1,0.05,covm,NULL,T)
x1 <- matrix(0,nrow = n,ncol = T)
x2 <- matrix(0,nrow = n,ncol = T)
for (i in (1:n)) {
  x1[i,] <- gp(1,T,1,0.05,covm,NULL,(T))
  x2[i,] <- gp(1,T,1,0.05,covm,NULL,(T))
}
x <- list("x1"=x1,"x2"=x2)
```

```{r}
d <- data.frame("t" <- 1:T,"path"=mupri)
plot(d,type="l")
```

```{r}
#hyperparameter

kmu <- 0.1
kx <- 0.1
covm <- function(g,k,t1,t2){
  res <- g*exp(-k*(t1-t2)^2)
  return(res)
}
KMU <- sapply(1:T, function(t1){
    sapply(1:T, function(t2){
      covm(1,kmu,t1,t2)
    })
  })
KX <- sapply(1:T, function(t1){
    sapply(1:T, function(t2){
      covm(1,kx,t1,t2)
    })
  })
in_prod <- function(z){
  temp <- apply(z, 2, function(v){return(apply(z, 2, function(u){return(u*v)}))})
  temp <- array(temp,dim = c(T,n,n))
  temp <- aperm(temp,perm = c(2,3,1))
  temp <- apply(temp, 3, function(t){
    diag(t) <- 0
    return(t)})
  temp <- array(temp,dim = c(n,n,T))
  return(temp)
}
```

```{r}
result <- matrix(0,nrow = T,ncol = 10)
time_vem <- rep(0,10)
mse <- rep(0,10)
for (sp in 1:10) {
  set.seed(sp)
  s <- list()
  pi <- list()
  y <- list()
  for (t in (1:T)) {
    temp1 <- matrix(0,nrow = n,ncol = n)
  
    temp2 <- matrix(0,nrow = n,ncol = n)
    temp3 <- matrix(0,nrow = n,ncol = n)
    for (i in (2:n)) {
      for (j in (1:(i-1))) {
        temp1[j,i] <- mupri[t]+x1[i,t]*x1[j,t]#+x2[i,t]*x2[j,t]
        temp2[j,i] <- 1/(1+exp(-temp1[j,i]))
        temp3[j,i] <- rbinom(1,1,temp2[j,i])
      }
    }
    s[[t]] <- temp1
    pi[[t]] <- temp2
    y[[t]] <- temp3
  }
  z <- array(0,dim = c(n,n,(T)))
for (t in 1:T) {
  for (i in (2:n)) {
    for (j in 1:(i-1)) {
      z[j,i,t] <- y[[t]][j,i]
    }
  }
   z[,,t][lower.tri(z[,,t])] <- t(z[,,t])[lower.tri(t(z[,,t]))]
}
y <- z
result_vem <- vem(n,T,100,KMU,KX,y)
mse[sp] <- norm(result_vem-mupri,type = "2")
result[,sp] <- result_vem
time_vem[sp] <- system.time(vem(n,T,100,KMU,KX,y))[3]
}
```

```{r}
par(mfrow = c(1,2))
plot(result[,which.min(mse)])
lines(mupri)
plot(result[,which.min(abs(mse-median(mse)))])
lines(mupri)
```

```{r}
quantile(time_vem)
```

